WikiCS:
  learning_rate: 0.01
  num_hidden: 256
  num_proj_hidden: 256
  activation: 'prelu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.3
  drop_feature_rate_1: 0.1
  drop_feature_rate_2: 0.1
  tau: 0.4
  num_epochs: 3000
  weight_decay: 0.00001
  drop_scheme: 'degree'
  rand_layers: 4

Cora:
  learning_rate: 0.0005
  num_hidden: 512
  num_proj_hidden: 512
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_embedding: 0.4
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.5
  drop_feature_rate_2: 0.5
  tau: 0.4
  num_epochs: 500
  weight_decay: 0.00001
  drop_scheme: 'degree'
  k_neighbors: 2
  rand_layers: 4
  K_layers: 8

Cora20:
  learning_rate: 0.0005
  num_hidden: 128
  num_proj_hidden: 128
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_embedding: 0.4
  drop_edge_rate_1: 0.5
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.5
  tau: 0.5
  num_epochs: 500
  weight_decay: 0.00005
  drop_scheme: 'degree'
  k_neighbors: 2
  rand_layers: 4
  K_layers: 8
PubMed:
  learning_rate: 0.002
  num_hidden: 512
  num_proj_hidden: 128
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_embedding: 0.4
  drop_edge_rate_1: 0.5
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.5
  tau: 0.4
  num_epochs: 900
  weight_decay: 0.00001
  drop_scheme: 'degree'
  k_neighbors: 2
  rand_layers: 4
  K_layers: 8

CiteSeer:
  learning_rate: 0.0001
  num_hidden: 512
  num_proj_hidden: 512
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_embedding: 0.4
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.3
  rand_layers: 2
  tau: 0.8
  num_epochs: 600
  weight_decay: 0.00001
  drop_scheme: 'degree'
  K_layers: 4
  k_neighbors: 1

CiteSeer20:
  learning_rate: 0.00001
  num_hidden: 512
  num_proj_hidden: 512
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_embedding: 0.4
  drop_edge_rate_1: 0.3
  drop_edge_rate_2: 0.2
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.2
  rand_layers: 2
  tau: 0.9
  num_epochs: 400
  weight_decay: 0.000001
  drop_scheme: 'degree'
  K_layers: 4
  k_neighbors: 1
ogbn-arxiv:
  learning_rate: 0.0001
  num_hidden: 128
  num_proj_hidden: 128
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_embedding: 0.4
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.2
  drop_feature_rate_1: 0.2
  drop_feature_rate_2: 0.2
  tau: 0.8
  num_epochs: 500
  weight_decay: 0.0000
  drop_scheme: 'degree'
  K_layers: 4
  rand_layers: 2
  k_neighbors: 1
Amazon-Computers:
   learning_rate: 0.0008
   num_hidden: 256
   num_proj_hidden: 256
   activation: "rrelu"
   base_model: 'GCNConv'
   num_layers: 2
   drop_edge_rate_1: 0.7
   drop_edge_rate_2: 0.2
   drop_feature_rate_1: 0.2
   drop_feature_rate_2: 0.2
   tau: 0.3
   num_epochs: 2000
   weight_decay: 0.00001
   drop_scheme: 'degree'
   rand_layers: 2
Amazon-Photo:
   learning_rate: 0.001
   num_hidden: 256
   num_proj_hidden: 256
   activation: "prelu"
   base_model: 'GCNConv'
   num_layers: 2
   drop_embedding: 0.10
   drop_edge_rate_1: 0.3
   drop_edge_rate_2: 0.4
   drop_feature_rate_1: 0.2
   drop_feature_rate_2: 0.3
   tau: 0.3
   k_layers: 4
   k_neighbors: 2
   num_epochs: 1500
   weight_decay: 0.000000
   drop_scheme: 'degree'
   rand_layers: 4
Coauthor-CS1:
   learning_rate: 0.0005
   num_hidden: 256
   num_proj_hidden: 256
   activation: "rrelu"
   base_model: 'GCNConv'
   num_layers: 2
   drop_embedding: 0.3
   drop_edge_rate_1: 0.3
   drop_edge_rate_2: 0.2
   drop_feature_rate_1: 0.3
   drop_feature_rate_2: 0.4
   tau: 0.4
   num_epochs: 1000
   weight_decay: 0.00001
   drop_scheme: 'degree'
   rand_layers: 4
Coauthor-CS:
   learning_rate: 0.0005
   num_hidden: 256
   num_proj_hidden: 256
   activation: "rrelu"
   base_model: 'GCNConv'
   num_layers: 2
   drop_embedding: 0.3
   drop_edge_rate_1: 0.3
   drop_edge_rate_2: 0.2
   drop_feature_rate_1: 0.3
   drop_feature_rate_2: 0.4
   tau: 0.4
   num_epochs: 1000
   weight_decay: 0.00001
   drop_scheme: 'degree'
   rand_layers: 4
Coauthor-Phy:
   learning_rate: [0.01]
   num_hidden: [128]
   num_proj_hidden: [64]
   activation: ["rrelu"]
   base_model: ['GCNConv']
   num_layers: [2]
   drop_edge_rate_1: [0.4]
   drop_edge_rate_2: [0.1]
   drop_feature_rate_1: [0.1]
   drop_feature_rate_2: [0.4]
   tau: [0.5]
   num_epochs: [15]
   weight_decay: [0.00001]
   drop_scheme: ['degree']
   rand_layers: [4]
ACM: #25-35
   learning_rate: [0.001,1e-4,2e-4]
   num_hidden: [64,128,256]
   num_proj_hidden: [64,128,256]
   activation: ["rrelu","relu"]
   base_model: ['GCNConv']
   num_layers: [2]
   drop_edge_rate_1: [0.2]
   drop_edge_rate_2: [0.2]
   drop_feature_rate_1: [0.1]
   drop_feature_rate_2: [0.4]
   tau: [0.5]
   num_epochs: [45]
   weight_decay: [1e-6,0]
   drop_scheme: ['degree']
   rand_layers: [3]
   patience: 20
   seed: [111,222,333,444,555]
   randNums1: [2,4,5] 
   randNums2: [2,4,5] 
   randNums3: [6,8,10] 
   randNums4: [6,8,10] 

dblp:
   learning_rate: [0.001,0.005,0.002,1e-4,2e-4,5e-4,1e-5,2e-5,5e-5]
   num_hidden: [64,128,256]
   num_proj_hidden: [64,128,256]
   activation: ["rrelu","relu"]
   base_model: ['GCNConv']
   num_layers: [2,3,4,5]
   drop_edge_rate_1: [0.2]
   drop_edge_rate_2: [0.2]
   drop_feature_rate_1: [0.1]
   drop_feature_rate_2: [0.4]
   tau: [0.5]
   num_epochs: [200,500,1000,1500,2000]
   weight_decay: [1e-4,1e-5,1e-6,0]
   drop_scheme: ['degree']
   rand_layers: [4]
   patience: 20
   seed: [111,222,333,444]

Freebase:
   learning_rate: [0.001,1e-4,2e-4]
   num_hidden: [64,128,256]
   num_proj_hidden: [64,128,256]
   activation: ["rrelu","relu"]
   base_model: ['GCNConv']
   num_layers: [2]
   drop_edge_rate_1: [0.2]
   drop_edge_rate_2: [0.2]
   drop_feature_rate_1: [0.1]
   drop_feature_rate_2: [0.4]
   tau: [0.5]
   num_epochs: [25,40]
   weight_decay: [1e-4,1e-5,1e-6,0]
   drop_scheme: ['degree']
   rand_layers: [4]
   patience: 20
   seed: [111,222,333,444,555]

Aminer: #40
   learning_rate: [0.001,1e-4,2e-4]
   num_hidden: [64,128]
   num_proj_hidden: [64,128]
   activation: ["rrelu","relu"]
   base_model: ['GCNConv']
   num_layers: [2]
   drop_edge_rate_1: [0.2]
   drop_edge_rate_2: [0.2]
   drop_feature_rate_1: [0.1]
   drop_feature_rate_2: [0.4]
   tau: [0.5]
   num_epochs: [45]
   weight_decay: [1e-6,0]
   drop_scheme: ['degree']
   rand_layers: [3]
   patience: 20
   seed: [111,222,333,444,555]
   randNums1: [2,4,5] 
   randNums2: [2,4,5] 
   randNums3: [6,8,10] 
   randNums4: [6,8,10] 

Test:
    learning_rate: [0.001]
    num_hidden: [256]
    num_proj_hidden: [256]
    activation: ["rrelu","relu"]
    base_model: ['GCNConv']
    num_layers: [2]
    drop_edge_rate_1: [0.2]
    drop_edge_rate_2: [0.2]
    drop_feature_rate_1: [0.1]
    drop_feature_rate_2: [0.4]
    tau: [0.5]
    num_epochs: [1000]
    weight_decay: [1e-4]
    drop_scheme: ['degree']
    rand_layers: [4]
    patience: 80000
    seed: [111]
    randNums1: [2] 
    randNums2: [2] 
    randNums3: [10] 
    randNums4: [10] 
